"""Veritabanını gerçekçi demo verileriyle dolduran script.

Çalıştırmak için: python seed_data.py
"""
from database import SessionLocal, init_db
from models import Department

DEPARTMENTS_SEED_DATA: list[dict[str, object]] = [
    {
        "university_name": "Akdeniz Üniversitesi",
        "faculty_name": "İktisadi ve İdari Bilimler Fakültesi",
        "department_name": "Yönetim Bilişim Sistemleri",
        "score_type": "EA",
        "education_type": "Örgün",
        "city": "Antalya",
        "quota_2025": 60,
        "rank_2023": 85000,
        "rank_2024": 78000,
        "rank_2025": 72000,
        "score_2025": 425.5,
        "user_demand_count": 340,
    },
    {
        "university_name": "İstanbul Teknik Üniversitesi",
        "faculty_name": "Bilgisayar ve Bilişim Fakültesi",
        "department_name": "Bilgisayar Mühendisliği",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "İstanbul",
        "quota_2025": 130,
        "rank_2023": 2600,
        "rank_2024": 2400,
        "rank_2025": 2200,
        "score_2025": 515.2,
        "user_demand_count": 1200,
    },
    {
        "university_name": "Orta Doğu Teknik Üniversitesi",
        "faculty_name": "İktisadi ve İdari Bilimler Fakültesi",
        "department_name": "İktisat (İngilizce)",
        "score_type": "EA",
        "education_type": "Örgün",
        "city": "Ankara",
        "quota_2025": 90,
        "rank_2023": 18000,
        "rank_2024": 16500,
        "rank_2025": 15800,
        "score_2025": 460.1,
        "user_demand_count": 610,
    },
    {
        "university_name": "Boğaziçi Üniversitesi",
        "faculty_name": "Mühendislik Fakültesi",
        "department_name": "Bilgisayar Mühendisliği",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "İstanbul",
        "quota_2025": 80,
        "rank_2023": 700,
        "rank_2024": 650,
        "rank_2025": 600,
        "score_2025": 525.8,
        "user_demand_count": 1500,
    },
    {
        "university_name": "Hacettepe Üniversitesi",
        "faculty_name": "Tıp Fakültesi",
        "department_name": "Tıp",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "Ankara",
        "quota_2025": 200,
        "rank_2023": 3200,
        "rank_2024": 3100,
        "rank_2025": 3050,
        "score_2025": 518.4,
        "user_demand_count": 980,
    },
    {
        "university_name": "Ankara Üniversitesi",
        "faculty_name": "Hukuk Fakültesi",
        "department_name": "Hukuk",
        "score_type": "SÖZ",
        "education_type": "Örgün",
        "city": "Ankara",
        "quota_2025": 300,
        "rank_2023": 9500,
        "rank_2024": 9000,
        "rank_2025": 8700,
        "score_2025": 445.6,
        "user_demand_count": 720,
    },
    {
        "university_name": "Gazi Üniversitesi",
        "faculty_name": "Eğitim Fakültesi",
        "department_name": "Rehberlik ve Psikolojik Danışmanlık",
        "score_type": "SÖZ",
        "education_type": "Örgün",
        "city": "Ankara",
        "quota_2025": 70,
        "rank_2023": 22000,
        "rank_2024": 21000,
        "rank_2025": 20500,
        "score_2025": 410.2,
        "user_demand_count": 300,
    },
    {
        "university_name": "Marmara Üniversitesi",
        "faculty_name": "İşletme Fakültesi",
        "department_name": "İşletme (İngilizce)",
        "score_type": "EA",
        "education_type": "Örgün",
        "city": "İstanbul",
        "quota_2025": 100,
        "rank_2023": 25000,
        "rank_2024": 24500,
        "rank_2025": 24200,
        "score_2025": 400.7,
        "user_demand_count": 250,
    },
    {
        "university_name": "Ege Üniversitesi",
        "faculty_name": "Tıp Fakültesi",
        "department_name": "Tıp",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "İzmir",
        "quota_2025": 180,
        "rank_2023": 6200,
        "rank_2024": 6000,
        "rank_2025": 5900,
        "score_2025": 505.3,
        "user_demand_count": 540,
    },
    {
        "university_name": "Dokuz Eylül Üniversitesi",
        "faculty_name": "Mühendislik Fakültesi",
        "department_name": "Elektrik-Elektronik Mühendisliği",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "İzmir",
        "quota_2025": 90,
        "rank_2023": 32000,
        "rank_2024": 33500,
        "rank_2025": 35000,
        "score_2025": 385.4,
        "user_demand_count": 180,
    },
    {
        "university_name": "Bilkent Üniversitesi",
        "faculty_name": "Mühendislik Fakültesi",
        "department_name": "Bilgisayar Mühendisliği",
        "score_type": "SAY",
        "education_type": "Burslu",
        "city": "Ankara",
        "quota_2025": 60,
        "rank_2023": 1200,
        "rank_2024": 1100,
        "rank_2025": 1000,
        "score_2025": 520.9,
        "user_demand_count": 890,
    },
    {
        "university_name": "Sabancı Üniversitesi",
        "faculty_name": "Mühendislik ve Doğa Bilimleri Fakültesi",
        "department_name": "Bilgisayar Bilimi ve Mühendisliği",
        "score_type": "SAY",
        "education_type": "Burslu",
        "city": "İstanbul",
        "quota_2025": 50,
        "rank_2023": 1800,
        "rank_2024": 1700,
        "rank_2025": 1650,
        "score_2025": 517.3,
        "user_demand_count": 760,
    },
    {
        "university_name": "Koç Üniversitesi",
        "faculty_name": "İktisadi ve İdari Bilimler Fakültesi",
        "department_name": "Ekonomi",
        "score_type": "EA",
        "education_type": "Burslu",
        "city": "İstanbul",
        "quota_2025": 40,
        "rank_2023": 4500,
        "rank_2024": 4300,
        "rank_2025": 4100,
        "score_2025": 470.8,
        "user_demand_count": 430,
    },
    {
        "university_name": "Yıldız Teknik Üniversitesi",
        "faculty_name": "Elektrik-Elektronik Fakültesi",
        "department_name": "Elektronik ve Haberleşme Mühendisliği",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "İstanbul",
        "quota_2025": 80,
        "rank_2023": 28000,
        "rank_2024": 27000,
        "rank_2025": 26500,
        "score_2025": 395.6,
        "user_demand_count": 210,
    },
    {
        "university_name": "İstanbul Üniversitesi",
        "faculty_name": "Edebiyat Fakültesi",
        "department_name": "Psikoloji",
        "score_type": "SÖZ",
        "education_type": "Örgün",
        "city": "İstanbul",
        "quota_2025": 60,
        "rank_2023": 41000,
        "rank_2024": 39500,
        "rank_2025": 38000,
        "score_2025": 375.1,
        "user_demand_count": 380,
    },
    {
        "university_name": "Çukurova Üniversitesi",
        "faculty_name": "Ziraat Fakültesi",
        "department_name": "Tarım Ekonomisi",
        "score_type": "EA",
        "education_type": "Örgün",
        "city": "Adana",
        "quota_2025": 50,
        "rank_2023": 95000,
        "rank_2024": 98000,
        "rank_2025": 101000,
        "score_2025": 355.2,
        "user_demand_count": 90,
    },
    {
        "university_name": "Erciyes Üniversitesi",
        "faculty_name": "Mühendislik Fakültesi",
        "department_name": "Bilgisayar Mühendisliği",
        "score_type": "SAY",
        "education_type": "İkinci Öğretim",
        "city": "Kayseri",
        "quota_2025": 70,
        "rank_2023": 110000,
        "rank_2024": 108000,
        "rank_2025": 105000,
        "score_2025": 340.5,
        "user_demand_count": 150,
    },
    {
        "university_name": "Selçuk Üniversitesi",
        "faculty_name": "Diş Hekimliği Fakültesi",
        "department_name": "Diş Hekimliği",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "Konya",
        "quota_2025": 60,
        "rank_2023": 14500,
        "rank_2024": 14000,
        "rank_2025": 13600,
        "score_2025": 495.7,
        "user_demand_count": 460,
    },
    {
        "university_name": "Akdeniz Üniversitesi",
        "faculty_name": "Tıp Fakültesi",
        "department_name": "Tıp",
        "score_type": "SAY",
        "education_type": "Örgün",
        "city": "Antalya",
        "quota_2025": 150,
        "rank_2023": 8200,
        "rank_2024": 8000,
        "rank_2025": 7900,
        "score_2025": 500.9,
        "user_demand_count": 500,
    },
    {
        "university_name": "İstanbul Teknik Üniversitesi",
        "faculty_name": "İşletme Fakültesi",
        "department_name": "İşletme Mühendisliği",
        "score_type": "EA",
        "education_type": "Örgün",
        "city": "İstanbul",
        "quota_2025": 60,
        "rank_2023": 12000,
        "rank_2024": 11500,
        "rank_2025": 11000,
        "score_2025": 455.3,
        "user_demand_count": 610,
    },
]


def seed_departments() -> None:
    """Departments tablosunu temizleyip demo verileriyle yeniden doldurur."""
    init_db()
    db = SessionLocal()
    try:
        db.query(Department).delete()
        db.add_all(Department(**row) for row in DEPARTMENTS_SEED_DATA)
        db.commit()
        print(f"{len(DEPARTMENTS_SEED_DATA)} bölüm başarıyla veritabanına eklendi.")
    finally:
        db.close()


if __name__ == "__main__":
    seed_departments()
